-- 创建站内消息表
CREATE TABLE IF NOT EXISTS `message` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '消息ID',
    `sender_id` BIGINT COMMENT '发送者ID(系统消息为NULL)',
    `sender_name` VARCHAR(100) COMMENT '发送者名称',
    `receiver_id` BIGINT NOT NULL COMMENT '接收者ID',
    `receiver_name` VARCHAR(100) NOT NULL COMMENT '接收者名称',
    `message_type` VARCHAR(20) NOT NULL COMMENT '消息类型: system/user/reservation/approval/reminder',
    `title` VARCHAR(200) NOT NULL COMMENT '消息标题',
    `content` TEXT NOT NULL COMMENT '消息内容',
    `related_id` BIGINT COMMENT '关联ID(预约ID/审批ID等)',
    `related_type` VARCHAR(50) COMMENT '关联类型(reservation/approval等)',
    `is_read` TINYINT DEFAULT 0 COMMENT '是否已读: 0-未读 1-已读',
    `priority` TINYINT DEFAULT 0 COMMENT '优先级: 0-普通 1-重要 2-紧急',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `read_time` DATETIME COMMENT '阅读时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记: 0-未删除 1-已删除',
    INDEX `idx_receiver_id` (`receiver_id`),
    INDEX `idx_sender_id` (`sender_id`),
    INDEX `idx_message_type` (`message_type`),
    INDEX `idx_is_read` (`is_read`),
    INDEX `idx_priority` (`priority`),
    INDEX `idx_create_time` (`create_time`),
    INDEX `idx_deleted` (`deleted`),
    INDEX `idx_receiver_read` (`receiver_id`, `is_read`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站内消息表';
